version: '3.4'

#This a compose file that is used for debugging and testing the main unit, thermostats and the database. The compose.yml for production (includung the frontend) can be found at the root directory of the project.
services:

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: database
    environment:
       #No root username and password are set here because the container is running in the docker bridge network
       #If a username of password is set here the connection string for the MainUnit needs to be modified
       MONGO_INITDB_DATABASE: heatHubDb

  mainunit:
    image: ${DOCKER_REGISTRY-}mainunit
    #image: haschmasch/mainunit
    container_name: mainunit
    depends_on:
        - mongo
    build:
      context: .
      dockerfile: MainUnit/Dockerfile
    ports:
      - "8085:8080"
    environment:
        #27017 is the default mongodb port. Since docker comes with a built in dns, the names of the containers can be used (instead of the ip addresses)
        MongoDbSettings__ConnectionString: mongodb://database:27017
        #Database and collection names can be freely specified and changed. The MongoDb driver will automatically create the new database/collections
        MongoDbSettings__DatabaseName: heatHubDb
        MongoDbSettings__RoomCollectionName: rooms
        MongoDbSettings__RoomTemperatureCollectionName: roomTemperatures
        MongoDbSettings__ThermostatCollectionName: thermostats
        MongoDbSettings__AuthCollectionName: userLogins

  thermostat:
    image: ${DOCKER_REGISTRY-}thermostat
    container_name: ${TERMOSTAT1_NAME}
    depends_on:
        - mainunit
    build:
      context: .
      dockerfile: Thermostat/Dockerfile
    environment:
        MainUnitURL: ${MAINUNIT_URL}
        ThermostatName: ${TERMOSTAT1_NAME}
  
  thermostat2:
    image: ${DOCKER_REGISTRY-}thermostat
    container_name: ${TERMOSTAT2_NAME}
    depends_on:
        - mainunit
    build:
      context: .
      dockerfile: Thermostat/Dockerfile
    environment:
        MainUnitURL: ${MAINUNIT_URL}
        ThermostatName: ${TERMOSTAT2_NAME}
  
  thermostat3:
    image: ${DOCKER_REGISTRY-}thermostat
    container_name: ${TERMOSTAT3_NAME}
    depends_on:
        - mainunit
    build:
      context: .
      dockerfile: Thermostat/Dockerfile
    environment:
        MainUnitURL: ${MAINUNIT_URL}
        ThermostatName: ${TERMOSTAT3_NAME}

  thermostat4:
    image: ${DOCKER_REGISTRY-}thermostat
    container_name: ${TERMOSTAT4_NAME}
    depends_on:
        - mainunit
    build:
      context: .
      dockerfile: Thermostat/Dockerfile
    environment:
        MainUnitURL: ${MAINUNIT_URL}
        ThermostatName: ${TERMOSTAT4_NAME}

  thermostat5:
    container_name: ${TERMOSTAT5_NAME}
    depends_on:
        - mainunit
    build:
      context: .
      dockerfile: Thermostat/Dockerfile
    environment:
        MainUnitURL: ${MAINUNIT_URL}
        ThermostatName: ${TERMOSTAT5_NAME}

networks:
  default:
    driver: bridge
