name: Trivy Container Scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-20.04"
    steps:
      #- name: Checkout code
      #  uses: actions/checkout@v4

      #- name: Build an image from Dockerfile
      #  run: |
      #    docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner for Mainunit
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/haschmasch/mainunit:latest'
          cache-dir: '/tmp/trivycache'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-mainunit.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for Thermostat
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/haschmasch/thermostat:latest'
          cache-dir: '/tmp/trivycache'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-thermostat.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results for Mainunit to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-mainunit.sarif'

      - name: Upload Trivy scan results for Thermostat to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-thermostat.sarif'
