name: Frontend Security Inspection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Use the PHP version of your project
          extensions: mbstring, tokenizer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --working-dir=Frontend/src

      - name: Run PHPStan (Static Analysis)
        run: |
          mkdir -p logs
          Frontend/src/vendor/bin/phpstan analyse Frontend/src/app --level=6 > logs/phpstan.log || true
        continue-on-error: true  # Ensure pipeline does not break

      - name: Upload PHPStan Log as Artifact
          uses: actions/upload-artifact@v3
          with:
          name: phpstan-log
          path: logs/phpstan.log

      #- name: Run PHP Security Audit (phpcs-security-audit)
       # run: |
        #  composer require phpcs-security-audit --dev
         # vendor/bin/phpcs --standard=vendor/pheromone/phpcs-security-audit/security.xml .
