# .github/workflows/masterflow.yml
name: Master Workflow

on:
  push:
    branches:
      - master  # Adjust the trigger as needed
      - master-flow

jobs:
  run-githubaction-a-and-b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Run githubaction-a
      #- name: Run GitHub Action A
        #uses: ./.github/workflows/codeql.yml

      # Run githubaction-b
     # - name: Run GitHub Action B
       # uses: ./.github/workflows/container-scan.yml

      # Run githubaction-b
     # - name: Run GitHub Action C
        #uses: ./.github/workflows/dotnet.yml

      # Run githubaction-b
      - name: Run GitHub Action D
        uses: ./.github/workflows/frontend-security-inspection.yml